# netlify.toml
[build]
  functions = "netlify/functions"  # Where your serverless functions are located
  publish = ".next" # Directory of your Next.js build output (e.g., .next)

[functions]
  external_node_modules = ["express", "mongoose", "cors", "cookie-parser"]  # Include necessary modules

[[redirects]]
  from = "/api/*"  #  Route all /api/* requests to your function
  to = "/.netlify/functions/api/:splat" #  :splat captures the rest of the path
  status = 200